prompt: "follow the man in red"
default_model: yolo11n
switch:
  short_gap: 2
  long_gap: 15
  cooldown_frames: 60
clip:
  base_thresh: 0.70
  tight_thresh: 0.80
  loose_thresh: 0.60
  margin_delta: 0.05
bridge:
  default: 8
  high_motion: 4
  stable: 12
provider:
  name: ultralytics        # ultralytics | roboflow | replicate | hf
  model_id: "your_model_id"
  timeout_s: 10

ultra:
  api_key: "aee3b7c66e472496b54163e97b1f4c2583cf75c567"
  models:
    yolo11n: "https://predict-blqihm1lbrzviglu81xc-7nza6zqsha-ew.a.run.app"
    yolo11m: "https://predict-fgerkqvofxwg6vttanta-7nza6zqsha-ew.a.run.app"
    yolo11x: "https://predict-gjreehgdl2pc13wg7puc-7nza6zqsha-ew.a.run.app"

# 本地模型配置
weights: "yolo11n.pt"  # 默认使用YOLO11n
local_models:
  yolo11n: "yolo11n.pt"
  yolo11m: "yolo11m.pt" 
  yolo11x: "yolo11x.pt"